display_errors = On
display_startup_errors = On
error_reporting = E_ALL

upload_max_filesize = 20M
post_max_size = 20M

date.timezone = Europe/Moscow

opcache.enable = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
